version: '3'

services:
  server:
    container_name: backend
    restart: unless-stopped
    build: .
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db
    ports:
      - "8081:8081"
    networks:
      - app-network
    command: npm start
  db:
    container_name: mongodb
    restart: unless-stopped
    image: mongo
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
    expose:
      - "27017"
networks:
  app-network:
    driver: bridge
volumes:
  dbdata: